# Ui changes
ui:
  - changed-files:
      - any-glob-to-any-file: 'src/ui/**'
      - any-glob-to-any-file: 'tests/ui/**'
      - any-glob-to-any-file: '*.qrc'
      - any-glob-to-any-file: '*.conf'

# Backend changes
backend:
  - changed-files:
      - any-glob-to-any-file: 'src/backend/**'
      - any-glob-to-any-file: 'tests/backend/**'

# Core Infrastructure changes
core:
  - changed-files:
      - any-glob-to-any-file: 'src/backend/core/**'

# Installer changes
installer:
  - changed-files:
      - any-glob-to-any-file: 'installer/**'

# Build system changes
build-system:
  - changed-files:
      - any-glob-to-any-file: 'cmake/**'
      - any-glob-to-any-file: 'scripts/**'
      - any-glob-to-any-file: '**/CMakeLists.txt'

# Workflow changes
workflows:
  - changed-files:
      - any-glob-to-any-file: '.github/**'

# Documentation changes
documentation:
  - changed-files:
      - any-glob-to-any-file: '*.md'