template: |
  ### Changes and updates in release v$RESOLVED_VERSION
  $CHANGES
  
  **Full Changelog:** https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'User Interface changes'
    labels:
      - 'ui'

  - title: 'Backend logical changes'
    labels:
      - 'backend'
    exclude-labels:
      - 'core'

  - title: 'Core System updates'
    labels:
      - 'core'

  - title: 'Installer and Deployment'
    labels:
      - 'installer'

  - title: 'Build System updates'
    labels:
      - 'build-system'
    # Hide build changes if they are part of a feature PR
    exclude-labels:
      - 'ui'
      - 'backend'
      - 'core'
    
  - title: 'Workflow and Tooling changes'
    labels:
      - 'workflows'

  - title: 'Documentation updates'
    labels:
      - 'documentation'

exclude-labels:
  - 'skip-changelog'

# Convert "## Title" to "**Title**"
replacers:
  - search: '/^## (.*)$/gm'
    replace: '**$1**'